#!/usr/bin/env python

import os, sys
print "extracting dumps..."
os.system( " (cd djangophylocore; tar xvzf dumps.tar.gz )" )

python_version = ".".join( "".join( os.popen("python -V 2>&1").read().split()).split(".")[:-1]).lower()
if sys.platform == 'darwin':
    python_path = "/usr/lib/%s/djangophylocore" % python_version
else:
    python_path = "/usr/lib/%s/site-packages/djangophylocore" % python_version

print "installing djangophylocore into %s" % python_path
os.system( "ln -sf `pwd`/djangophylocore %s" % python_path )

print "intalling phylocore"
os.system( "( cd phylocore; sudo ./install )" )
