#!/usr/bin/env python

import os
localDir = os.path.dirname(__file__)
path_to = os.path.join(os.getcwd(), localDir)

init = """import os
os.environ['DJANGO_SETTINGS_MODULE'] = '%s/settings'
from django.conf import settings
#try:
#    settings.DATABASE_NAME = '%s/phylocore.db'
#except:
#    pass
from djangophylocore.models import *
try:
    from djangophylocore.models import *
except:
    print "cannot import djangophylocore"
""" % ( path_to, path_to )
#open( './__init__.py', 'w' ).write( init )

python_version = ".".join( "".join( os.popen("python -V 2>&1").read().split()).split(".")[:-1]).lower()
os.system( "(cd ..; ln -sf `pwd`/phylocore /usr/local/lib/%s/site-packages/phylocore )" % python_version )
